import { defineStore } from 'pinia'
import { type Training, TrainingSchema } from '@/types/TrainingSchema.ts'
import { useBaseStore } from '@/composables/useBaseStore.ts'
import { computed } from 'vue'

const storageName = 'trainings'

export const useTrainingStore = defineStore(storageName, () => {
  const baseStore = useBaseStore<Training>(storageName, TrainingSchema, 'localStorage', {
    createdAt: 'ctime',
    updatedAt: 'mtime',
  })

  // Getters
  const trainingsSortedByDate = computed(() =>
    [...baseStore.items.value].sort((a, b) => b.ctime.getTime() - a.ctime.getTime()),
  )
  const trainingsCount = computed(() => baseStore.items.value.length)

  // Actions
  async function createTraining() {
    // ID is auto-generated by createItem
    // ctime/mtime are auto-set by createItem
    return baseStore.createItem({
      name: 'Entrainement ' + (baseStore.items.value.length + 1).toString(),
      exercices: [],
    })
  }

  async function saveTraining(training: Training) {
    return baseStore.updateItem(training)
  }

  return {
    ...baseStore,
    trainings: baseStore.items, // Alias for compatibility
    trainingsSortedByDate,
    trainingsCount,
    createTraining,
    saveTraining,
    getTrainingById: baseStore.getItemById,
    deleteTrainingById: async (id: string) => {
      await baseStore.deleteItem(id)
    },
    getTrainings: async () => {
      await baseStore.ensureLoaded()
      return trainingsSortedByDate.value
    },
    loadTrainings: baseStore.loadItems,
    persistTrainings: baseStore.persistItems,
  }
})
